# This Message defines the tracked target position and size in the image.
# The position and size has been normalized with respect to width and height of image.
# Center of image is (0, 0), the horizontal axis is x, and the vertical axis is y.

float32 center_x		#direction of right is positive, -1 ... 1.
float32 center_y		#direction of up is positive, -1 ... 1.
float32 size_x		#size of target 
float32 size_y		#size of target 